//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameShipConfigurations
    {
        public int id { get; set; }
        public string coordinate { get; set; }
        public string playerFK { get; set; }
        public int gameFK { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Players Players { get; set; }
    }
}
